apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    kapp.k14s.io/identity: v1;/apiextensions.k8s.io/CustomResourceDefinition/builds.kpack.io;apiextensions.k8s.io/v1
    kapp.k14s.io/original: '{"apiVersion":"apiextensions.k8s.io/v1","kind":"CustomResourceDefinition","metadata":{"labels":{"kapp.k14s.io/app":"1643567221581143006","kapp.k14s.io/association":"v1.9f28fb82003d035266fadaaf2cd721d6"},"name":"builds.kpack.io"},"spec":{"conversion":{"strategy":"Webhook","webhook":{"clientConfig":{"service":{"name":"kpack-webhook","namespace":"kpack","path":"/convert","port":443}},"conversionReviewVersions":["v1"]}},"group":"kpack.io","names":{"categories":["kpack"],"kind":"Build","listKind":"BuildList","plural":"builds","shortNames":["cnbbuild","cnbbuilds","bld","blds"],"singular":"build"},"scope":"Namespaced","versions":[{"additionalPrinterColumns":[{"jsonPath":".status.latestImage","name":"Image","type":"string"},{"jsonPath":".status.conditions[?(@.type==\"Succeeded\")].status","name":"Succeeded","type":"string"}],"name":"v1alpha1","schema":{"openAPIV3Schema":{"type":"object","x-kubernetes-preserve-unknown-fields":true}},"served":true,"storage":false,"subresources":{"status":{}}},{"additionalPrinterColumns":[{"jsonPath":".status.latestImage","name":"Image","type":"string"},{"jsonPath":".status.conditions[?(@.type==\"Succeeded\")].status","name":"Succeeded","type":"string"}],"name":"v1alpha2","schema":{"openAPIV3Schema":{"type":"object","x-kubernetes-preserve-unknown-fields":true}},"served":true,"storage":true,"subresources":{"status":{}}}]}}'
    kapp.k14s.io/original-diff-md5: c6e94dc94aed3401b5d0f26ed6c0bff3
  creationTimestamp: "2022-01-30T18:27:34Z"
  generation: 4
  labels:
    kapp.k14s.io/app: "1643567221581143006"
    kapp.k14s.io/association: v1.9f28fb82003d035266fadaaf2cd721d6
  name: builds.kpack.io
  resourceVersion: "69987664"
  uid: 55770a41-3925-4d51-ac00-57735b38870e
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNRVENDQWVlZ0F3SUJBZ0lSQUpib1UzTzRYVzB6UWtSeVFjcVkzOTh3Q2dZSUtvWkl6ajBFQXdJd09ERVUKTUJJR0ExVUVDaE1MYTI1aGRHbDJaUzVrWlhZeElEQWVCZ05WQkFNVEYydHdZV05yTFhkbFltaHZiMnN1YTNCaApZMnN1YzNaak1CNFhEVEl5TURJeE1qQTROVEV6TUZvWERUSXlNREl4T1RBNE5URXpNRm93T0RFVU1CSUdBMVVFCkNoTUxhMjVoZEdsMlpTNWtaWFl4SURBZUJnTlZCQU1URjJ0d1lXTnJMWGRsWW1odmIyc3VhM0JoWTJzdWMzWmoKTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFMFFoeFhJSTVZRXN0aUJPRVdodmFJcmd1QVEwMwpIaFJ5MDZlOW40YjVOZTFsVkMxU3BVVlN0NFdualZlUHZuYUhsQnRnTUNVckwrUjhlWGFtaDNrWXlhT0IwVENCCnpqQU9CZ05WSFE4QkFmOEVCQU1DQW9Rd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3RUdDQ3NHQVFVRkJ3TUMKTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3SFFZRFZSME9CQllFRkk4Y3dpUDlhN2Q4dXhLTnpzZjhMU3FVcE44cQpNRzBHQTFVZEVRUm1NR1NDRFd0d1lXTnJMWGRsWW1odmIydUNFMnR3WVdOckxYZGxZbWh2YjJzdWEzQmhZMnVDCkYydHdZV05yTFhkbFltaHZiMnN1YTNCaFkyc3VjM1pqZ2lWcmNHRmpheTEzWldKb2IyOXJMbXR3WVdOckxuTjIKWXk1amJIVnpkR1Z5TG14dlkyRnNNQW9HQ0NxR1NNNDlCQU1DQTBnQU1FVUNJSHdiclVFZXRMbm52Qm1yakV1Zwoycjg3bmNOdWJvbzJwSDh6MCtWSHlyUDZBaUVBOTgvcnliNDhKb0V2cm01Q3ZGNFpabWJ5eGZVaUdKMzBWc2luCmoyQW90Ums9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
        service:
          name: kpack-webhook
          namespace: kpack
          path: /convert
          port: 443
      conversionReviewVersions:
      - v1
  group: kpack.io
  names:
    categories:
    - kpack
    kind: Build
    listKind: BuildList
    plural: builds
    shortNames:
    - cnbbuild
    - cnbbuilds
    - bld
    - blds
    singular: build
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.latestImage
      name: Image
      type: string
    - jsonPath: .status.conditions[?(@.type=="Succeeded")].status
      name: Succeeded
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: false
    subresources:
      status: {}
  - additionalPrinterColumns:
    - jsonPath: .status.latestImage
      name: Image
      type: string
    - jsonPath: .status.conditions[?(@.type=="Succeeded")].status
      name: Succeeded
      type: string
    name: v1alpha2
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    categories:
    - kpack
    kind: Build
    listKind: BuildList
    plural: builds
    shortNames:
    - cnbbuild
    - cnbbuilds
    - bld
    - blds
    singular: build
  conditions:
  - lastTransitionTime: "2022-01-30T18:27:36Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: "2022-01-30T18:27:37Z"
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1alpha2
